version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 14018:27017
        environment:
            # creating a database when container is initialised
            - MONGO_INITDB_DATABASE=appdata
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=6372363723
        volumes:
            - mongo-db:/data/db
            - mongo-configdb:/data/configdb

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        environment:
            - NODE_ENV=production
            # Секретный ключ для проверки клиентского токена
            - AUTH_PRIVATE_KEY=f91eb2d2-c8d5-4cef-9b25-fec0e7b06882
            # Токен доступа к серверу лицензирования
            - AUTH_LIC_SERVER_API_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MTE3NDM4MTMsImV4cCI6MTY0MzI3OTgxMywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSJ9.ceBR9Q3IKlGaFjBxAvJmeZ2UaOXhK5A2miMfcC2HwyY
            # DB_URI
            - DB_URI=admin:6372363723@mongo:14018/appdata
            # Server Port
            - PORT=8080
            # Swagger Doc Path
            - SWAGGER_ROUTE=/docs
            # LicServer
            - LIC_SERVER_HOST=http://127.0.0.1:8079
        depends_on:
            - mongo
        ports:
            - 8080:8080

volumes:
    # Configure shared volumes to be used in the services above.
    mongo-db:
    mongo-configdb: