version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        hostname: mongo
        command: mongod --port 27018
        ports:
            - 27018:27018
        networks:
            - app-network
        environment:
            # creating a database when container is initialised
            #- MONGO_INITDB_ROOT_USERNAME=tornado
            #- MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=appdata
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongo-db:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_PORT=27018
            - ME_CONFIG_MONGODB_SERVER=mongo
            #- ME_CONFIG_MONGODB_ADMINUSERNAME=tornado
            #- ME_CONFIG_MONGODB_ADMINPASSWORD=password
        networks:
            - app-network

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        environment:
            # Секретный ключ для проверки клиентского токена
            - AUTH_PRIVATE_KEY=f91eb2d2-c8d5-4cef-9b25-fec0e7b06882
            # Токен доступа к серверу лицензирования
            - AUTH_LIC_SERVER_API_KEY=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MTE3NDM4MTMsImV4cCI6MTY0MzI3OTgxMywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSJ9.ceBR9Q3IKlGaFjBxAvJmeZ2UaOXhK5A2miMfcC2HwyY
            # DB_URI
            - DB_URI=mongo:27018
            - DB_NAME=appdata
            # Server Port
            - PORT=8080
            # Swagger Doc Path
            - SWAGGER_ROUTE=/docs
            # LicServer
            - LIC_SERVER_HOST=http://192.168.8.110:8078
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8080:8080
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    # Configure shared volumes to be used in the services above.
    mongo-db: