export enum ErrorCodes {
    UNKNOWN = 1,
    CLIENT_TOKEN_EMPTY_TOKEN = 2,
    CLIENT_TOKEN_VERIFICATION = 3,
    CLIENT_TOKEN_BAD_FORMAT = 4,
    INTEGRATION_TOKEN_EMPTY_TOKEN = 32,
    INTEGRATION_TOKEN_VERIFICATION = 33,
    INTEGRATION_TOKEN_BAD_FORMAT = 34,
    TERMINAL_TOKEN_EMPTY_TOKEN = 101,
    TERMINAL_TOKEN_BAD_FORMAT = 102,
    TERMINAL_TOKEN_CHECK_LICENSE_ERROR = 103,
}