export enum ErrorCodes {
    UNKNOWN,
    CLIENT_TOKEN_EMPTY_TOKEN,
    CLIENT_TOKEN_VERIFICATION,
    CLIENT_TOKEN_BAD_FORMAT,
    TERMINAL_TOKEN_EMPTY_TOKEN,
    TERMINAL_TOKEN_BAD_FORMAT,
    TERMINAL_TOKEN_CHECK_LICENSE_ERROR,
}