export enum RefTypes {
    ASSETS = "assets",
    SELECTORS = "selectors",
    PRODUCTS = "products",
    CURRENCIES = "currencies",
    ORDER_TYPES = "order-types",
    NODES = "nodes",
    TAGS = "tags",
    BUSINESS_PERIODS = "business-periods",
    ADS = "ads",
    LANGUAGES = "languages",
    TRANSLATIONS = "translations",
    STORES = "stores",
    TERMINALS = "terminals",
    LICENSES = "licenses",
}